server:
  port: 8877

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: ${COMPUTERNAME:localhost}

spring:
  application:
    name: spring-gateway
  cloud:
    gateway:
      routes:
        - id: msCustomer
          uri: lb://MICROSERVICE-CUSTOMER
          predicates:
            - Path=/ms-customer/***
        - id: msAccount
          uri: lb://MICROSERVICE-ACCOUNT
          predicates:
            - Path=/ms-account/***
        - id: msCredit
          uri: lb://MICROSERVICE-CREDIT
          predicates:
            - Path=/ms-credit/***
        - id: msTransferer
          uri: lb://MICROSERVICE-TRANSFERER
          predicates:
            - Path=/ms-transferer/***
        - id: msMovementBank
          uri: lb://MICROSERVICE-MOVEMENT-BANK
          predicates:
            - Path=/ms-movement-bank/***
        - id: msOperation
          uri: lb://MICROSERVICE-OPERATIONS
          predicates:
            - Path=/ms-operation/***
